### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by milaneyia** [milaneyia/obwc#2]
submissions:
- [ ] add a countdown with remaining time on submission page (ask kaetwo for main page design)
- [ ] read some sort of format to assign anon names of entries to all at once (regraz uses a script to edit the osz, or see the possibility to port the script to the site instead)
- [ ] "we were trying to update on the website but the date isnt changing" - check if update date is actually working

judging:
- [x] order judging by anom name by default to avoid switching order everytime
- [x] make the scoring panel fixed when scrolling "it kinda sucks when i want to rate bottom diffs"
- [ ] "also why cant we use decimal this time too." confirm if decimals for scoring matter/should be an option
- [ ] "Also where's the auto saving function iirc last year we have this" - no idea what it is
- [ ] separate "save changes" button for the general comment? less confusing
- [ ] make comment section a bit taller
- [ ] recheck conditions while saving to avoid duplicates again zz also block buttons in the ui to avoid weird stuff

results:
- [ ] finish page design (only missing detail modal)
- [ ] start thinking how to "remove" eliminated teams (either save on db/cache or calculate everytime ew)
- [x] add sorting (in some automatic way inside DateTable component)
- [ ] show detail in "all" rounds, by round (?
